[tool.poetry]
name = "ezlog"
version = "0.1.0"
description = ""
authors = ["Yohan Poirier-Ginter <pg.yohan@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
